# -*- coding: utf-8 -*-
"""B-4/B-5感度分析の直列スイープドライバー（mt5bt run を1点ずつ実行）。
- mt5bt optimizeの12エージェント並列はディスクを食い尽くすため使わない
- resume安全: results/<NAME>/summary.csv が既にあれば再実行しない
- 失敗時: terminal64をkillして次へ（最後にFAIL一覧を出す）
出力: scratchpad/fwd/b45_sweep.csv（point,window,param,net,pf,dd_pct,winrate,trades）
"""
import csv
import os
import re
import subprocess
import sys
import time
from pathlib import Path

MT5BT = r"C:\Users\f\AppData\Local\Python\pythoncore-3.14-64\Scripts\mt5bt.exe"
REPO = Path(__file__).resolve().parents[1]
CFG_DIR = REPO / "ml" / "b45_work"
OUT = CFG_DIR / "b45_sweep.csv"
CFG_DIR.mkdir(parents=True, exist_ok=True)

WINDOWS = {"IS": ("2021.06.21", "2026.06.20"), "OOS": ("2016.06.21", "2021.06.20")}

TEMPLATE = """# auto-generated by sweep_b45.py
mt5_path: "C:\\\\Users\\\\f\\\\AppData\\\\Roaming\\\\XMTrading MT5\\\\terminal64.exe"

expert:    "SCA_EA"
symbol:    "GBPJPY"
period:    "M15"
from_date: "{frm}"
to_date:   "{to}"

deposit:  100000
currency: "JPY"
leverage: 25

model: "every_tick"

parameters:
  RangeStartHour:    0
  RangeEndHour:      9
  TradeEndHour:      12
  ForceCloseHour:    22
  MinRange_ATRd:     0.30
  MaxRange_ATRd:     1.00
  Break_Buffer_ATRd: 0.0
  SL_Mode:           0
  SL_ATRd_Mult:      0.5
  RR_Ratio:          2.0
  OneShotPerDir:     true
  UseD1TrendFilter:  false
  MaxSpreadPoints:   0
  LotSize:           0.01
  UseRiskSizing:     false
  MagicNumber:       20261001
  UseReversalBoost:  {boost}
  Boost_MinDrift_ATRd: {k}
  RangeShiftLow_Pips:  {shift}
  RangeShiftHigh_Pips: 0.0
  ResultFileName:    "{name}_r.csv"

report_dir:  "results"
report_name: "{name}"
"""


def parse_summary(path):
    if not path.exists():
        return None
    d = {}
    with open(path, newline="", encoding="utf-8-sig", errors="replace") as fh:
        for row in csv.reader(fh):
            if len(row) >= 2:
                d[row[0].strip()] = row[1].strip()
    def num(key):
        v = d.get(key, "")
        v = v.replace(",", "").replace("%", "")
        try:
            return float(v)
        except ValueError:
            return None
    net = num("純利益")
    if net is None:
        return None
    return {"net": net, "pf": num("プロフィットファクター"), "dd_pct": num("最大DD%"),
            "winrate": num("勝率"), "trades": num("総取引数")}


def points():
    pts = []
    for w in ("IS", "OOS"):
        pts.append(("B5_%s_NOBOOST" % w, w, False, 0.0, 0.0))
        for shift in range(-10, 11):
            tag = ("P%02d" % shift) if shift >= 0 else ("M%02d" % -shift)
            pts.append(("B4_%s_%s" % (w, tag), w, True, 0.0, float(shift)))
        for k in (0.05, 0.10, 0.15, 0.20):
            pts.append(("B5_%s_K%02d" % (w, int(round(k * 100))), w, True, k, 0.0))
    return pts


def main():
    all_pts = points()
    done, fails = [], []
    t0 = time.time()
    for idx, (name, w, boost, k, shift) in enumerate(all_pts, 1):
        summ = REPO / "results" / name / "summary.csv"
        r = parse_summary(summ)
        if r is None:
            frm, to = WINDOWS[w]
            cfg = CFG_DIR / (name + ".yaml")
            cfg.write_text(TEMPLATE.format(frm=frm, to=to, name=name,
                                           boost="true" if boost else "false",
                                           k=("%.2f" % k), shift=("%.1f" % shift)),
                           encoding="utf-8")
            t1 = time.time()
            try:
                subprocess.run([MT5BT, "run", str(cfg)], cwd=str(REPO),
                               capture_output=True, text=True, timeout=1800)
            except subprocess.TimeoutExpired:
                pass
            r = parse_summary(summ)
            el = time.time() - t1
            if r is None:
                fails.append(name)
                print("[%2d/%d] %-14s FAIL (%.0fs) -> kill terminal" % (idx, len(all_pts), name, el), flush=True)
                subprocess.run(["taskkill", "/IM", "terminal64.exe", "/F"],
                               capture_output=True)
                time.sleep(3)
                continue
            print("[%2d/%d] %-14s net=%+9.0f pf=%.2f dd=%.1f%% n=%d (%.0fs)"
                  % (idx, len(all_pts), name, r["net"], r["pf"] or 0, r["dd_pct"] or 0,
                     r["trades"] or 0, el), flush=True)
        else:
            print("[%2d/%d] %-14s cached net=%+9.0f" % (idx, len(all_pts), name, r["net"]), flush=True)
        done.append({"point": name, "window": w, "boost": boost, "k": k, "shift": shift, **r})
        with open(OUT, "w", newline="", encoding="utf-8") as fh:
            wcsv = csv.DictWriter(fh, fieldnames=list(done[0].keys()))
            wcsv.writeheader()
            wcsv.writerows(done)
    print("TOTAL %.1f min, done=%d fail=%d %s"
          % ((time.time() - t0) / 60, len(done), len(fails), (": " + ",".join(fails)) if fails else ""), flush=True)


if __name__ == "__main__":
    main()
